name: Example papine backend

on:
  push:
    branches:
      - main
    paths:
      - studentTest
      - 'Docker-compose.yml'
      - .github/workflows/*_backend.yml
jobs:
  build-deploy:
    name: Build and Deploy Spring boot
    runs-on: Ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/student-project-kam:latest

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username:${{secrets.DOCKER_HUB_USERNAME}}
          password:${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/student-project-kam:latest